# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version)

<module 'numpy.version' from '/Users/vincentwakim/opt/anaconda3/lib/python3.9/site-packages/numpy/version.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
import numpy as np
a = np.random.rand(2,3,5)

In [ ]:
import numpy as np
a = np.random.random((2,3,5))

In [ ]:
import numpy as np
a = np.random.randn(2,3,5)

#### 4. Print *a*.


In [5]:
import numpy as np
a = np.random.rand(2,3,5)
print(a)

[[[0.31436173 0.6905308  0.41328282 0.57516894 0.50782599]
  [0.59367687 0.91754915 0.39548259 0.07655859 0.84667183]
  [0.74792517 0.93412597 0.6491004  0.3326922  0.47348283]]

 [[0.32941742 0.53540236 0.54215976 0.16665675 0.80565796]
  [0.86530735 0.35012775 0.40040396 0.0512922  0.37725434]
  [0.2910932  0.59946265 0.23595642 0.99970531 0.60083518]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
import numpy as np
b = np.ones((5,2,3))

#### 6. Print *b*.


In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
import numpy as np
a = np.random.rand(2,3,5)
b = np.ones((5,2,3))

print(np.array_equal(a.shape, b.shape))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# the shapes of a and b are not the same so not possible 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
import numpy as np
b = np.ones((5,2,3))
c = np.transpose(b, (1,2,0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
import numpy as np
a = np.random.rand(2,3,5)
b = np.ones((5,2,3))
c = np.transpose(b, (1,2,0))
d = a + c

# the shapes of a and c are the same and they have the same number of elements in each dimension

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
import numpy as np
a = np.random.rand(2,3,5)
b = np.ones((5,2,3))
c = np.transpose(b, (1,2,0))
d = a + c

print("a:\n", a)
print("d:\n", d)

# a is an array of random values, while d is the element-wise sum of a and c. 
#The values in d are equal to a plus 1, because c has all of its elements set to 1.

a:
 [[[0.50562951 0.21573209 0.25888888 0.23776994 0.22590349]
  [0.02140315 0.26977842 0.79528784 0.21124156 0.60802478]
  [0.54021015 0.38908813 0.84948384 0.76342293 0.122789  ]]

 [[0.2043629  0.24312417 0.87083057 0.25039504 0.28887498]
  [0.27457934 0.70446793 0.49575024 0.85945627 0.42842597]
  [0.75803958 0.25300397 0.70390493 0.90422211 0.14353756]]]
d:
 [[[1.50562951 1.21573209 1.25888888 1.23776994 1.22590349]
  [1.02140315 1.26977842 1.79528784 1.21124156 1.60802478]
  [1.54021015 1.38908813 1.84948384 1.76342293 1.122789  ]]

 [[1.2043629  1.24312417 1.87083057 1.25039504 1.28887498]
  [1.27457934 1.70446793 1.49575024 1.85945627 1.42842597]
  [1.75803958 1.25300397 1.70390493 1.90422211 1.14353756]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
import numpy as np
a = np.random.rand(2,3,5)
b = np.ones((5,2,3))
c = np.transpose(b, (1,2,0))
e = a * c
print(e)

[[[0.42055427 0.56217219 0.33079161 0.80432873 0.52346863]
  [0.09284567 0.29707615 0.54007057 0.18803928 0.40276994]
  [0.70998125 0.76325753 0.0141663  0.94472093 0.8539843 ]]

 [[0.53807432 0.84608728 0.03701766 0.03908163 0.45038452]
  [0.31938183 0.51636298 0.37174745 0.05786163 0.60673461]
  [0.7726913  0.84092961 0.72394861 0.52694692 0.05753538]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here